# Generated by Django 5.2.13 on 2026-06-09 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_laporan', models.DateField(unique=True)),
                ('total_transaksi', models.IntegerField(default=0)),
                ('total_pendapatan', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'laporan_harian',
            },
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('jumlah_pembelian', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_pembayaran', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tgl_beli', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembelian', to='obat.barang')),
            ],
            options={
                'db_table': 'pembelian',
            },
        ),
    ]
