# Generated by Django 5.2.13 on 2026-06-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengirim', models.CharField(max_length=100)),
                ('pesan', models.TextField()),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('tgl_chat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_pemesanan',
            },
        ),
    ]
