# Generated by Django 5.2.13 on 2026-06-09 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('pemasok', models.CharField(max_length=100)),
                ('jumlah_barang', models.IntegerField(default=0)),
                ('tgl_expired', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'barang',
            },
        ),
        migrations.CreateModel(
            name='DaftarHarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('harga_satuan', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harga', to='obat.barang')),
            ],
            options={
                'db_table': 'daftar_harga',
            },
        ),
        migrations.CreateModel(
            name='StokBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('jumlah_stok', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stok', to='obat.barang')),
            ],
            options={
                'db_table': 'stok_barang',
            },
        ),
    ]
